Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty32"

    config.vm.provider "virtualbox" do |v|
        v.name = "composite_dev"
        v.customize ['modifyvm', :id, '--memory', '1024']
        v.customize ['modifyvm', :id, '--cpus', '2']
        v.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
    end

    # Disable the default syncing
    config.vm.synced_folder ".", "/vagrant", disabled: true
    # Instead sync the actual composite folder
    config.vm.synced_folder "../", "/home/vagrant/composite"

    # Forward x11
    config.ssh.forward_x11 = true

    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get -y install make
        sudo apt-get -y install git
        sudo apt-get -y install ntp
        sudo apt-get -y install bc
        sudo apt-get -y install gcc-multilib
        sudo apt-get -y install binutils-dev
        sudo apt-get -y install binutils-dev
        sudo apt-get -y install qemu-kvm
    SHELL
end
